export const mockIssues = [
  {
    id: 1,
    category: 'lab',
    title: 'تلوث في عينة الاختبار',
    description: 'تم اكتشاف تلوث في عينة رقم A-204 أثناء الفحص الدوري.',
    severity: 'critical',
    status: 'open',
    createdBy: 'أحمد علي',
    createdAt: '2026-07-21T08:30:00',
    mediaType: 'image',
    mediaUrl: 'https://placehold.co/600x400?text=صورة+الإشكالية',
    comments: [],
  },
  {
    id: 2,
    category: 'filling',
    title: 'خلل في ماكينة التعبئة #3',
    description: 'الماكينة تتوقف بشكل متكرر عند الوصول لسرعة 80%.',
    severity: 'major',
    status: 'open',
    createdBy: 'سارة محمد',
    createdAt: '2026-07-21T09:15:00',
    mediaType: 'image',
    mediaUrl: 'https://placehold.co/600x400?text=صورة+الماكينة',
    comments: [],
  },
  {
    id: 3,
    category: 'production',
    title: 'انقطاع في خط الإنتاج B',
    description: 'توقف خط الإنتاج B لمدة 20 دقيقة بسبب عطل كهربائي.',
    severity: 'minor',
    status: 'closed',
    createdBy: 'كريم حسن',
    createdAt: '2026-07-20T14:00:00',
    mediaType: null,
    mediaUrl: null,
    comments: [],
  },
]
